### ISSUE TITLE
Get prompted after done with story

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#10]
## User Story
As a Student, I would like to be prompted to rate my tutor after I am done being their student so that I can easily give them a rating.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given the student unmatches with the tutor, then they are prompted to give the tutor a rating out of 5 stars, or can skip the rating
- [ ] Given the tutor unmatches with the student, then the student is sent a notification to rate the tutor
- [ ] Given the student clicks on the notification to rate the tutor, then the student is prompted to give the tutor a rating out of 5 stars, or can skip the rating.

**Comment by zhao19991111** [comment]
no longer needed
