### ISSUE TITLE
Create User Request Layout

### ISSUE THREAD

**Issue by GeraldDT5** [cs130-w21/bruintutor#15]
## User Story
As a Tutor, I would like to be able to view requests for booking a time slot so that I can determine whether a potential matching is good.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given a matching request from a student, then a tutor can see the option to view detail about the request #111 
- [x] Given a matching request from a student, then a tutor can accept or deny the request #111

**Comment by sammyli0106** [comment]
Linked with closed pull requests.
