### ISSUE TITLE
Tutors can view profiles of current students

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#21]
## User Story
As a Tutor, I would like to be able to click on the profiles of current and past students to view their profiles so that I can get information about my students.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given a Tutor clicks on the profile of a current or past student, then they should be taken to the corresponding profile page of the student.

**Comment by sammyli0106** [comment]
Contact List is done for first point.
