### ISSUE TITLE
Create Individual Tutor View Layout

### ISSUE THREAD

**Issue by davisgomes** [cs130-w21/bruintutor#22]
## User Story
As a user, I would like to view relevant information about a tutor so that I am able to make an informed decision when engaging in matching.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given a specified tutor, then produce a page that displays rating, availability, classes, and messaging box
- [x] Given a user wants to message a tutor, then give a message box that will be able to create a user comment
- [x] Given a user whats to match with a tutor, then the student will be able to use a button to engage in matching (duplicate with search and match functionality story)

**Comment by sammyli0106** [comment]
1, 2 are tested. Duplicate for 3
