### ISSUE TITLE
View profiles of current tutors

### ISSUE THREAD

**Issue by zhao19991111** [cs130-w21/bruintutor#23]
## User Story
As a Student, I would like to view profiles of my current tutors so that I could get an idea of their experience.

## Detailed Description
Students should be able to see a list of their current tutors.
Students should be able to click into tutors' profile pages and view their public personal information

## Acceptance Criteria
- [x] Given the user is a student, then the user should be able to see a list of all the matched tutors and click into their profiles

**Comment by sammyli0106** [comment]
First point is done along with contact list
