### ISSUE TITLE
Tutors can edit classes they can tutor

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#31]
## User Story
As a Tutor, I would like to be able to edit the current classes that I am offering to tutor from my profile page so that I can change incorrect or out-of-date information.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given a Tutor clicks on an "Edit Classes" button, then they should be taken to a page where they can add and remove classes from their current offerings list.
- [ ] Given a Tutor clicks on a save button, then they should be taken back to their profile page where they can see their updated information.

**Comment by sammyli0106** [comment]
Duplicate story. Combined this into story #28
